### ISSUE TITLE
Error: Symbol's function definition is void: nil

### ISSUE THREAD

**Issue by nuynait** [nhoffman/org-export#1]
I download emacs though brew using command 'brew install emacs' and I have GNU Emacs as well. My Mac Emacs version is 24.3.1 and org-mode version is 7.9.3f, however, when I run org-export, I encounter the following error

Symbol's function definition is void: nil

Here is the screen shot: [Click Here](http://shan.us/i6Jf)

Please take a look. Thank you very much for your time.

**Comment by nhoffman** [comment]
Hi Jerry,

Can you provide a minimal example of a file that reproduces the error?

Thanks,
Noah

**Comment by nuynait** [comment]
Sure. I just realized that this problem only exist on one of the org file. I previously thought it occurs on all the files. I think that the main difference for the file reproduces the error is that it has code insertion.

here is the file that reproduces the error: [Click Here](http://shan.us/i0vg)

**Comment by nhoffman** [comment]
Well, the not-very-satisfying answer is that I don't understand the origin of the error - these scripts are just a wrapper around org-mode itself, and the error arises from within org-mode (I did add a --verbose option if you'd like to inspect the traceback). A couple of things I do know: java isn't among the languages I've supported by default. I need to add support for adding language specifications (now issue #2). Also, as far as I know, the code block headers need to be aligned with the left margin (yours were indented). For what it's worth, since you aren't evaluating the code blocks, you could just enclose them in #+BEGIN_EXAMPLE ... #+END_EXAMPLE (although you will not have syntax highlighting). Sorry I can't be more helpful here... thanks for trying it out and for the feedback.
